"""Open the pull request. The PR is the product's real-world side effect.

Fork-to-fork on purpose: the demo targets are historical flakes whose upstream fixes merged
years ago, so a PR against upstream would be noise for the maintainer. On the user's fork the
PR is public, permanent and clickable, and it carries the evidence in its body.

Plain GitHub REST via httpx. No git push from the machine: the branch, the commit and the PR
are created through the API, so the only credential needed is one fine-grained token, and the
commit is attributed to that token's owner.
"""
import base64
import time
from pathlib import Path

import httpx

from agent import db
from agent.config import DASHBOARD_URL, DATA, GITHUB_API, GITHUB_OWNER, GITHUB_TOKEN


class GitHub:
    def __init__(self, token: str, owner: str, repo: str, api: str = GITHUB_API):
        self.owner, self.repo = owner, repo
        self.client = httpx.Client(base_url=api, timeout=30, headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        })

    # -- low level --
    def _req(self, method: str, path: str, ok=(200, 201), **kw) -> dict | list | None:
        r = self.client.request(method, path, **kw)
        if r.status_code == 404 and method == "GET":
            return None
        if r.status_code not in ok:
            raise RuntimeError(f"GitHub {method} {path} -> {r.status_code}: {r.text[:300]}")
        return r.json() if r.text else {}

    # -- repository --
    def repo_exists(self) -> bool:
        return self._req("GET", f"/repos/{self.owner}/{self.repo}") is not None

    def ensure_fork(self, upstream_owner: str) -> None:
        if self.repo_exists():
            return
        self._req("POST", f"/repos/{upstream_owner}/{self.repo}/forks", ok=(202,))
        for _ in range(30):                     # forks are created asynchronously
            time.sleep(2)
            if self.repo_exists():
                return
        raise RuntimeError("fork did not appear within 60s")

    def branch_sha(self, name: str) -> str | None:
        ref = self._req("GET", f"/repos/{self.owner}/{self.repo}/git/ref/heads/{name}")
        return ref["object"]["sha"] if ref else None

    def ensure_branch(self, name: str, sha: str) -> None:
        if self.branch_sha(name):
            return
        self._req("POST", f"/repos/{self.owner}/{self.repo}/git/refs",
                  json={"ref": f"refs/heads/{name}", "sha": sha})

    def commit_files(self, branch: str, base_sha: str, files: dict[str, bytes], message: str) -> str:
        """Point `branch` at one new commit on top of `base_sha` holding `files` byte for byte.

        One commit per pull request. Running it again replaces that commit instead of stacking a
        second one, so a corrected upload leaves a clean history."""
        prefix = f"/repos/{self.owner}/{self.repo}/git"
        base_commit = self._req("GET", f"{prefix}/commits/{base_sha}")
        tree = []
        for path, content in files.items():
            blob = self._req("POST", f"{prefix}/blobs",
                             json={"content": base64.b64encode(content).decode("ascii"), "encoding": "base64"})
            tree.append({"path": path, "mode": "100644", "type": "blob", "sha": blob["sha"]})
        new_tree = self._req("POST", f"{prefix}/trees", json={"base_tree": base_commit["tree"]["sha"], "tree": tree})
        commit = self._req("POST", f"{prefix}/commits",
                           json={"message": message, "tree": new_tree["sha"], "parents": [base_sha]})
        self._req("PATCH", f"{prefix}/refs/heads/{branch}", json={"sha": commit["sha"], "force": True})
        return commit["sha"]

    def find_pr(self, head: str, base: str) -> str | None:
        prs = self._req("GET", f"/repos/{self.owner}/{self.repo}/pulls",
                        params={"head": f"{self.owner}:{head}", "base": base, "state": "open"})
        return prs[0]["html_url"] if prs else None

    def create_pr(self, head: str, base: str, title: str, body: str) -> str:
        existing = self.find_pr(head, base)
        if existing:
            return existing
        pr = self._req("POST", f"/repos/{self.owner}/{self.repo}/pulls",
                       json={"title": title, "head": head, "base": base, "body": body})
        return pr["html_url"]


# ---- evidence ---------------------------------------------------------------------------------

def render_pr_body(attempt: dict, candidate: dict, summary: str, baseline: dict, verify: dict,
                   hypotheses: list[dict], refused: list[dict], dashboard_url: str = "") -> str:
    b_runs, b_pass = baseline["runs"], baseline["passes"]
    v_runs, v_pass = verify["runs"], verify["passes"]
    bound = 3 / v_runs if v_runs else 0
    lines = [
        summary.strip(), "",
        "## Evidence (generated by Flakeproof)",
        "",
        f"**Test:** `{attempt['test_name']}`  ",
        f"**Category:** {attempt.get('category') or 'unknown'}  ",
        f"**Root cause:** {attempt.get('root_cause') or 'see summary'}  ",
        "",
        "| Measurement | Result |",
        "|---|---|",
        f"| Before the patch | {b_pass}/{b_runs} runs passed under rotating Surefire orders |",
        f"| After the patch (Blade 1) | **{v_pass}/{v_runs}** runs passed under the same orders |",
        f"| Band-aid scan (Blade 2) | {candidate.get('blade2_verdict') or 'n/a'}: {candidate.get('blade2_reason') or ''} |",
        "",
        f"0 failures in {v_runs} runs bounds the true failure rate below {bound:.1%} at 95% confidence "
        f"(rule of three). This is proof to a stated confidence, not a proof of impossibility.",
        "",
    ]
    if hypotheses:
        lines += ["### Diagnosis trail", ""]
        for h in hypotheses:
            lines.append(f"- **{h['agent']}** ({h['category']}, {h['confidence']:.0%}): {h['summary']}")
        lines.append("")
    if refused:
        lines += ["### Candidates the gate refused for this test", ""]
        for r in refused:
            lines.append(f"- {r['title']} ({r['source']}): {r['verdict']}"
                         + (f" ({r['blade2_category']}: {r['blade2_reason']})" if r.get('blade2_category') else "")
                         + (f", Blade 1 {r['blade1_passes']}/{r['blade1_runs']}" if r.get('blade1_runs') else ""))
        lines.append("")
    if dashboard_url:
        lines.append(f"Full run, every rerun and the agent trace: {dashboard_url.rstrip('/')}/#attempt-{attempt['id']}")
        lines.append("")
    lines.append("_Flakeproof opens a pull request only for a fix it has proven and judged to be a "
                 "real fix rather than a mask. Repository: https://github.com/"
                 f"{GITHUB_OWNER}/flakeproof_")
    return "\n".join(lines)


def _committable_bytes(repo: Path, rel_paths: list[str]) -> dict[str, bytes]:
    """Each file exactly as `git commit` would store it: staged, then read back from the index.

    Reading the working tree in Python text mode would turn CRLF into LF, and the pull request
    would then rewrite every line of a CRLF file instead of changing only the patched lines."""
    from agent import repo as repo_ops
    files = {}
    for rel in rel_paths:
        repo_ops.git(repo, "add", "--", rel)
        files[rel] = repo_ops.git_bytes(repo, "show", f":{rel}")
    return files


def _patched_files(ctx, diff_text: str) -> dict[str, bytes]:
    """Apply the diff on a clean tree, capture the changed files byte for byte, reset."""
    from agent import repo as repo_ops
    repo_ops.reset_worktree(ctx.repo)
    ok, msg = repo_ops.apply_diff(ctx.repo, diff_text)
    if not ok:
        raise RuntimeError(f"verified patch no longer applies: {msg}")
    try:
        return _committable_bytes(ctx.repo, repo_ops.changed_files(ctx.repo))
    finally:
        repo_ops.reset_worktree(ctx.repo)


def open_pr_for_attempt(ctx, title: str, summary: str) -> tuple[str | None, Path]:
    """Create branch + commit + PR on the fork for the verified candidate. Returns (url, body_path)."""
    from agent import repo as repo_ops

    conn = ctx.conn
    attempt = db.rows(conn, "SELECT * FROM attempts WHERE id = ?", (ctx.attempt_id,))[0]
    cand = db.rows(conn, "SELECT * FROM candidates WHERE id = ?", (ctx.verified_candidate_id,))[0]
    if cand["verdict"] != "VERIFIED":
        raise RuntimeError("refusing: candidate is not VERIFIED")

    baseline = {"runs": ctx.baseline_total, "passes": ctx.baseline_passes}
    if not baseline["runs"]:
        b = db.runs_for(conn, ctx.attempt_id, phase="baseline")
        baseline = {"runs": len(b), "passes": sum(r["passed"] for r in b)}
    verify = {"runs": cand["blade1_runs"], "passes": cand["blade1_passes"]}
    hypotheses = db.rows(conn, "SELECT * FROM hypotheses WHERE attempt_id = ? ORDER BY id", (ctx.attempt_id,))
    refused = db.rows(conn, "SELECT * FROM candidates WHERE attempt_id = ? AND verdict LIKE 'REFUSED%'"
                            " ORDER BY ordinal", (ctx.attempt_id,))
    body = render_pr_body(attempt, cand, summary, baseline, verify, hypotheses, refused, DASHBOARD_URL)

    out_dir = DATA / "pr-bodies"
    out_dir.mkdir(parents=True, exist_ok=True)
    body_path = out_dir / f"attempt-{ctx.attempt_id}.md"
    body_path.write_text(f"# {title}\n\n{body}\n", encoding="utf-8")

    if not ctx.open_prs or not GITHUB_TOKEN:
        ctx.log("pr", "github", f"dry run: PR body saved to {body_path}")
        return None, body_path

    project_url = (ctx.project_url or "").rstrip("/")
    upstream_owner, repo_name = project_url.rsplit("/", 2)[-2:]
    gh = GitHub(GITHUB_TOKEN, GITHUB_OWNER, repo_name)
    gh.ensure_fork(upstream_owner)

    base_sha = repo_ops.head_sha(ctx.repo)
    base_branch = f"flakeproof/base-{base_sha[:10]}"
    head_branch = f"flakeproof/fix-{ctx.attempt_id}-{base_sha[:7]}"
    gh.ensure_branch(base_branch, base_sha)
    gh.ensure_branch(head_branch, base_sha)
    gh.commit_files(head_branch, base_sha, _patched_files(ctx, cand["diff"]),
                    f"{title}\n\nProposed by Flakeproof for {attempt['test_name']}")
    url = gh.create_pr(head_branch, base_branch, title, body)

    db.update(conn, "attempts", ctx.attempt_id, pr_url=url)
    ctx.log("pr", "github", url)
    print(f"  PR opened: {url}", flush=True)
    return url, body_path
